before_install:
- sudo apt-get -qq update
- sudo apt-get install -qq python-pyaudio
deploy:
  true:
    python: 2.7
    branch: master
    tags: true
  distributions: sdist bdist_wheel
install:
- python setup.py bdist_wheel
- pip install ./dist/*.whl
language: python
python:
- '2.6'
- '2.7'
- '3.4'
- '3.5'
- '3.6'
script: pytest
notifications:
  email: false
